name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Run Backend Unit Tests
        run: |
          cd backend
          npm test

      - name: Install Frontend Dependencies
        run: |
          cd frontend/GreenTrack
          yarn install
       -name: Run Frontend Unit Tests
        run: |
          cd frontend/GreenTrack
          yarn test --run


      - name: Build Frontend
        run: |
          cd frontend/GreenTrack
          yarn build
